name: ci

on:
  push:
  pull_request:

jobs:
  rocky-rpm:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch to TUNA mirrors (Rocky)
        run: |
          dnf -y makecache
          dnf -y update

      - name: Install build tools
        run: |
          dnf -y install git gcc gcc-c++ cmake make curl unzip tar pkgconfig findutils ninja

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install catch2

      - name: Configure
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          ninja -C build
