name: ci

on:
  push:
  pull_request:

jobs:
  rocky-rpm:
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:24.03
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 更新包缓存
        run: |
          dnf -y makecache
          dnf -y update

      - name: 安装构建工具
        run: |
          dnf -y install git gcc gcc-c++ cmake make curl unzip tar pkgconfig findutils ninja-build

      - name: 安装vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg "$VCPKG_ROOT"
          "$VCPKG_ROOT"/bootstrap-vcpkg.sh
          "$VCPKG_ROOT"/vcpkg install catch2

      - name: Configure
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT"/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          ninja -C build
